"""create users catalog subscriptions

Revision ID: 66d24407a20c
Revises: 
Create Date: 2026-07-26 17:13:18.901044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d24407a20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('default_cost', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('default_trial_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('default_cost >= 0', name='ck_catalog_default_cost_nonneg'),
    sa.CheckConstraint('default_trial_days >= 0', name='ck_catalog_trial_days_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_valid_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_expiration_date', sa.Date(), nullable=True),
    sa.CheckConstraint('cost >= 0', name='ck_subscriptions_cost_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('catalog_services')
    # ### end Alembic commands ###
